{% set name = "pynvml" %}
{% set version = "12.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gpuopenanalytics/{{ name }}/archive/{{ version }}.tar.gz
  sha256: b76ffc0e6e5b3c13f68e1903b28ce875f6f8e50315d0abd4b40f2ee68d02911a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  imports:
    - pynvml

about:
  home: https://github.com/gpuopenanalytics/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python Bindings for the NVIDIA Management Library
  description: |
    This is a wrapper around the NVML library. For information about
    the NVML library, see <http://developer.nvidia.com>.
  doc_url: https://pypi.org/project/pynvml/
  dev_url: https://github.com/gpuopenanalytics/pynvml

extra:
  recipe-maintainers:
    - rjzamora
