{% set name = "pynvml" %}
{% set version = "12.0.0" %}
{% set major_version = version.split(".")[0]|int %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 299ce2451a6a17e6822d6faee750103e25b415f06f59abb8db65d30f794166f5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - nvidia-ml-py ~={{ major_version }}.0
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - pynvml

about:
  home: https://github.com/gpuopenanalytics/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python Bindings for the NVIDIA Management Library
  description: |
    This is a wrapper around the NVML library. For information about
    the NVML library, see <http://developer.nvidia.com>.
  doc_url: https://pypi.org/project/pynvml/
  dev_url: https://github.com/gpuopenanalytics/pynvml

extra:
  recipe-maintainers:
    - rjzamora
