{% set name = "pynvml" %}
{% set version = "11.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gpuopenanalytics/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 4220af6fd94f7978413adc3ca306e0786f5e1a80888ef8984098f0ac751e8483

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  imports:
    - pynvml

about:
  home: https://github.com/gpuopenanalytics/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python Bindings for the NVIDIA Management Library
  description: |
    This is a wrapper around the NVML library. For information about
    the NVML library, see <http://developer.nvidia.com>.
  doc_url: https://pypi.org/project/pynvml/
  dev_url: https://github.com/gpuopenanalytics/pynvml

extra:
  recipe-maintainers:
    - rjzamora
